name: luminus
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Updated versions to resolve dependency conflicts
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  permission_handler: ^11.3.1
  record: ^6.0.1
  camera: ^0.11.0 # Updated to a version compatible with modern Gradle
  path_provider: ^2.1.3
  audioplayers: ^6.0.0
  video_player: ^2.8.6
  audio_waveforms: ^1.0.5
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
